const { SlashCommandBuilder, PermissionFlagsBits, ButtonBuilder, ButtonStyle, ActionRowBuilder, ChannelType } = require('discord.js');
const { getUser, getGuild, data, save } = require('../services/store');
const { awardSpellmarks } = require('../services/economy');
const { nymeraEmbed, COLORS } = require('../lib/theme');
const { audit } = require('../services/logging');
const { getVerification, setVerification } = require('../services/verification');

const defaultShop = [{ id: 'moon-tea', name: 'Moon Tea', price: 150, description: 'A calming collectible.' }, { id: 'haze-charm', name: 'Haze Charm', price: 500, description: 'A silver ward against dull evenings.' }];
module.exports = [
  { data: new SlashCommandBuilder().setName('shop').setDescription('Browse Nymera’s shop.'), async execute(i) { const g = await getGuild(i.guildId); const items = g.shop.length ? g.shop : defaultShop; await i.reply({ embeds: [nymeraEmbed('The Moonlit Shop', items.map(x => `**${x.id}** — ${x.name}: ${x.price} Spellmarks\n${x.description}`).join('\n\n'))] }); } },
  { data: new SlashCommandBuilder().setName('buy').setDescription('Purchase a shop item.').addStringOption(o => o.setName('item').setDescription('Item ID from /shop').setRequired(true)), async execute(i) { const g = await getGuild(i.guildId); const item = (g.shop.length ? g.shop : defaultShop).find(x => x.id === i.options.getString('item').toLowerCase()); const u = await getUser(i.guildId, i.user.id); if (!item) return i.reply({ content: 'That relic is not in the shop.', ephemeral: true }); if (u.spellmarks < item.price) return i.reply({ content: 'Your vault lacks the needed Spellmarks.', ephemeral: true }); u.spellmarks -= item.price; u.inventory.push(item.id); await save(); await i.reply({ embeds: [nymeraEmbed('A Relic Acquired', `You purchased **${item.name}**.`, COLORS.green)] }); } },
  { data: new SlashCommandBuilder().setName('inventory').setDescription('View your acquired items.'), async execute(i) { const u = await getUser(i.guildId, i.user.id); await i.reply({ embeds: [nymeraEmbed('Your Satchel', u.inventory.length ? u.inventory.map(x => `• ${x}`).join('\n') : 'Your satchel is empty.')] , ephemeral: true }); } },
  { data: new SlashCommandBuilder().setName('coinflip').setDescription('Flip a coin for Spellmarks.').addStringOption(o => o.setName('side').setDescription('Your call').addChoices({ name: 'Heads', value: 'heads' }, { name: 'Tails', value: 'tails' }).setRequired(true)).addIntegerOption(o => o.setName('bet').setDescription('Spellmarks to bet').setMinValue(1).setRequired(true)), async execute(i) { const u = await getUser(i.guildId, i.user.id); const bet = i.options.getInteger('bet'); if (u.spellmarks < bet) return i.reply({ content: 'Your vault lacks that wager.', ephemeral: true }); const result = Math.random() < .5 ? 'heads' : 'tails'; const win = result === i.options.getString('side'); u.spellmarks += win ? bet : -bet; await save(); await i.reply({ embeds: [nymeraEmbed('Coin of the Veil', `It lands on **${result}**. ${win ? `You gain **${bet}** Spellmarks.` : `You lose **${bet}** Spellmarks.`}`, win ? COLORS.green : COLORS.danger)] }); } },
  { data: new SlashCommandBuilder().setName('trivia').setDescription('Answer a gothic trivia question.'), async execute(i) { const answer = Math.random() < .5 ? 'raven' : 'moon'; await i.reply({ embeds: [nymeraEmbed('A Question from the Archives', `What watches the midnight sky in Nymera’s favorite omen? Answer with `/ask` if you need a clue.\n\nThe archival answer for this round is **${answer}**.`)] }); } },
  { data: new SlashCommandBuilder().setName('verify').setDescription('Set up or complete member verification.').addSubcommand(s => s.setName('setup').setDescription('Post a verification button.').addChannelOption(o => o.setName('channel').setDescription('Verification channel').addChannelTypes(ChannelType.GuildText).setRequired(true)).addRoleOption(o => o.setName('role').setDescription('Role granted after verification').setRequired(true))).addSubcommand(s => s.setName('status').setDescription('View verification settings.')), async execute(i) { const action = i.options.getSubcommand(); const verification = await getVerification(i.guildId); if (action === 'status') return i.reply({ embeds: [nymeraEmbed('Verification Status', verification.channelId ? `Channel: <#${verification.channelId}>\nRole: <@&${verification.roleId}>` : 'Verification has not been configured.')], ephemeral: true }); if (!i.memberPermissions.has(PermissionFlagsBits.ManageGuild)) return i.reply({ content: 'Only server managers may set verification.', ephemeral: true }); const channel = i.options.getChannel('channel'), role = i.options.getRole('role'); if (!role.editable) return i.reply({ content: 'Move Nymera above that role first.', ephemeral: true }); await setVerification(i.guildId, { channelId: channel.id, roleId: role.id }); const button = new ButtonBuilder().setCustomId('nymera_verify').setLabel('Verify').setStyle(ButtonStyle.Success); await channel.send({ embeds: [nymeraEmbed('Enter the Hazeground', 'Read the rules, then press the seal to receive access.')], components: [new ActionRowBuilder().addComponents(button)] }); await i.reply({ content: 'Verification panel posted.', ephemeral: true }); } },
  { data: new SlashCommandBuilder().setName('giveaway').setDescription('Manage a giveaway.').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s => s.setName('create').setDescription('Create a button-entry giveaway.').addStringOption(o => o.setName('prize').setDescription('Prize').setRequired(true)).addIntegerOption(o => o.setName('minutes').setDescription('Duration').setMinValue(1).setMaxValue(10080).setRequired(true))).addSubcommand(s => s.setName('end').setDescription('End a giveaway.').addStringOption(o => o.setName('id').setDescription('Giveaway ID').setRequired(true))).addSubcommand(s => s.setName('list').setDescription('List active giveaways.')), async execute(i) { const action = i.options.getSubcommand(); if (action === 'list') { const list = Object.values(data.giveaways).filter(g => g.guildId === i.guildId && !g.ended); return i.reply({ embeds: [nymeraEmbed('Active Giveaways', list.length ? list.map(g => `**${g.id}** — ${g.prize} • ${g.entries.length} entries`).join('\n') : 'None are active.')], ephemeral: true }); } const id = i.options.getString('id') || Math.random().toString(36).slice(2, 8); if (action === 'end') { const g = data.giveaways[id]; if (!g || g.ended) return i.reply({ content: 'No active giveaway bears that ID.', ephemeral: true }); g.ended = true; const winner = g.entries.length ? g.entries[Math.floor(Math.random() * g.entries.length)] : null; await save(); return i.reply({ embeds: [nymeraEmbed('Giveaway Ended', winner ? `**${g.prize}** goes to <@${winner}>!` : `No entries were made for **${g.prize}**.`)] }); } const prize = i.options.getString('prize'), minutes = i.options.getInteger('minutes'); data.giveaways[id] = { id, guildId: i.guildId, channelId: i.channelId, prize, endsAt: Date.now() + minutes * 60000, entries: [], ended: false }; await save(); const button = new ButtonBuilder().setCustomId(`giveaway:${id}`).setLabel('Enter giveaway').setStyle(ButtonStyle.Primary); await i.reply({ embeds: [nymeraEmbed('A Prize Emerges', `**${prize}**\nEnds <t:${Math.floor((Date.now() + minutes * 60000) / 1000)}:R>\nGiveaway ID: ${id}`)], components: [new ActionRowBuilder().addComponents(button)] }); } },
  { data: new SlashCommandBuilder().setName('invites').setDescription('View invite attribution.').addSubcommand(s => s.setName('me').setDescription('View your invite count.')).addSubcommand(s => s.setName('leaderboard').setDescription('View invite leaders.')), async execute(i) { const list = Object.values(data.invites).filter(x => x.guildId === i.guildId).sort((a,b) => b.count - a.count); if (i.options.getSubcommand() === 'me') { const mine = list.find(x => x.userId === i.user.id); return i.reply({ embeds: [nymeraEmbed('Your Invitations', `Verified joins attributed to you: **${mine?.count || 0}**.`)], ephemeral: true }); } await i.reply({ embeds: [nymeraEmbed('Invite Chronicle', list.length ? list.slice(0,10).map((x,n) => `**${n+1}.** <@${x.userId}> — ${x.count}`).join('\n') : 'No tracked invitations yet.')] }); } }
];
